### ISSUE TITLE
utilisation du mode graphique de Resip sous environnement windows (10)

### ISSUE THREAD

**Issue by akakeronos** [ProgrammeVitam/sedatools#1]
J'essaye d'utiliser Resip en mode interface graphique et je n'arrive pas à lancer le programme.
J'ai téléchargé un jre dans le dossier Resip et j'ai la configuration suivante : 

dossier Resip : 
Config
jre>bin/java
Logs
Resip.bat
Resip.exe

Lorsque je double-clique sur l'exécutable rien ne se passe. 

Est-ce qu'il y a d'autres choses à faire pour faire fonctionner ce programme ?

**Comment by croftophile** [comment]
Bonjour,
Si je ne me trompe pas, il faut installer sur le poste (sur lequel vous désirez faire fonctionner ReSip) un JRE 8 avant de pouvoir faire fonctionner resip. L'installation du JRE doit positionner dans la variable système PATH l'emplacement des éxécutables java, nécessaire pour le bon usage de ReSip.
Nous allons mettre la documentation à jour.
Cordialement,
Olivier

**Comment by akakeronos** [comment]
Bonjour,
Merci pour votre réponse.
Depuis je suis passé sous un environnement linux (ubuntu 18.04) et je rencontre à nouveau une difficulté.

Après avoir installé un jdk et maven j'ai lancé la commande mvn clean install comme indiqué dans la doc

j'ai l'erreur suivante

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project java-libpst: MavenReportException: Error while creating archive: Unable to find javadoc command: The javadoc executable '/usr/lib/jvm/default-java/bin/javadoc' doesn't exist or is not a file. Verify the JAVA_HOME environment variable. -> [Help 1]
[ERROR] 

ma variable JAVA_HOME est /usr/lib/jvm/default-java

**Comment by croftophile** [comment]
Bonjour,

Pour compiler sedatools, il faut effectivement un JDK. 
L'erreur que vous indiquez est que le binaire javadoc n'existe pas sous "/usr/lib/jvm/default-java/bin/javadoc". Je suppose que ``/usr/lib/jvm/default-java`` est un lien symbolique ; il faudrait idéalement vérifier que ce lien pointe bie sur un JDK et non un JRE.
Cordialement,
Olivier

**Comment by akakeronos** [comment]
Bonjour,
J'ai remplacé le lien symbolique par le lien vers le jdk /usr/lib/jvm/java-11-openjdk-amd64 mais la compilation produit la même erreur The javadoc executable '/usr/lib/jvm/java-11-openjdk-amd64/bin/javadoc' doesn't exist or is not a file

Cordialement
Pascal

**Comment by akakeronos** [comment]
est-ce qu'il faut installer javadoc comme un plugin de maven ? http://maven-plugins.sourceforge.net/installing.html

**Comment by akakeronos** [comment]
en commentant les lignes relatives au plugin javadoc dans le fichier pom.xml ça passe

**Comment by JSLair** [comment]
Resip n'est pas encore compatible Jdk11 il est seulement jdk8 à ce stade.

**Comment by akakeronos** [comment]
Ah ok. Je vais modifier mon installation pour passer sur un jdk plus ancien que celui installé avec ubuntu 18.04. Merci

**Comment by akakeronos** [comment]
Je viens d'essayer d'installer une version plus ancienne du jdk sur ma mahcine en suivant ce tutoriel https://tecadmin.net/install-oracle-java-8-ubuntu-via-ppa/ et j'ai une fin de non-recevoir :)

sudo apt-get install oracle-java8-installer
Aucune version du paquet oracle-java8-installer n'est disponible, mais il existe dans la base
de données. Cela signifie en général que le paquet est manquant, qu'il est devenu obsolète
ou qu'il n'est disponible que sur une autre source

Est-ce que vous savez comme faire pour récupérer un jdk compatible avec Resip sur ubuntu 18.04 ?
Merci d'avance
Pascal

**Comment by akakeronos** [comment]
J'ai trouvé https://doc.ubuntu-fr.org/openjdk !

**Comment by akakeronos** [comment]
A priori j'ai passé les 2 premères étapes mais j'ai une erreur sur la compilation de sedatools et je sèche une peu...

INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for sedatools 2.0.0-SNAPSHOT:
[INFO] 
[INFO] sedatools .......................................... SUCCESS [  0.269 s]
[INFO] sedalib ............................................ SUCCESS [ 24.497 s]
[INFO] sedalib-samples .................................... SUCCESS [  8.908 s]
[INFO] mailextractlib ..................................... SUCCESS [01:47 min]
[INFO] mailextract ........................................ FAILURE [ 18.138 s]
[INFO] resip .............................................. SKIPPED
[INFO] testsipgenerator ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:39 min
[INFO] Finished at: 2019-09-23T16:18:10+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.15:launch4j (l4j-clui) on project mailextract: Failed to build the executable; please verify your configuration.: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/home/pascal/.m2/repository/net/sf/launch4j/launch4j/3.9/launch4j-3.9-workdir-linux/bin/windres": error=2, Aucun fichier ou dossier de ce type -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.15:launch4j (l4j-clui) on project mailextract: Failed to build the executable; please verify your configuration.


Caused by: java.io.IOException: Cannot run program "/home/pascal/.m2/repository/net/sf/launch4j/launch4j/3.9/launch4j-3.9-workdir-linux/bin/windres": error=2, Aucun fichier ou dossier de ce type

 
Il faut installer le plugin launch4j-maven-plugin ?

**Comment by JSLair** [comment]
Il y a des prérequis pour l'utilisation de Launch4j https://github.com/lukaszlenart/launch4j-maven-plugin#faq.

PS: j'ai regardé et normalement je viens de commiter une version des sedatools qui est compatible jdk11 à la compilation et à l'exécution

**Comment by croftophile** [comment]
Re-,
Pour préciser les propos de Jean-Séverin, sur nos environnements de build  de sedatools (CentOS), nous installons en prérequis les packages système suivants :
mingw-binutils-generic zlib.i686 ncurses-libs.i686 bzip2-libs.i686
pour le bon fonctionnement de launch4j

Cordialement,
Olivier

**Comment by akakeronos** [comment]
Tout d'abord merci pour votre aide et votre patience :)
J'ai installé lib32z1 lib32ncurses5 et finalement j'ai réussi à compiler sedatools

Je lance ensuite java -jar target/resip-2.0.0-SNAPSHOT-shaded.jar en espérant voir l'interface graphique s'afficher mais rien ne semble se passer.

En lançant la commande 

java -jar target/resip-2.0.0-SNAPSHOT-shaded.jar -d /home/pascal/Nextcloud/stencil/  -w tmp -x

j'ai comme message 

19:37:33.141 [ResipApp] INFO  GLOBAL - Début du journal au niveau=GLOBAL
19:37:33.145 [ResipApp] INFO  GLOBAL - Resip.GraphicApp: Le fichier de préférences global "ResipPreferences.properties" n'a pas été trouvé. Recherche de la version personnelle.
->Impossible d'importer les préférences
19:37:33.145 [ResipApp] INFO  GLOBAL - Resip.GraphicApp: Le fichier de préférences personnel "/home/pascal/.Resip/ResipPreferences.properties" n'a pas non plus été trouvé. Ce fichier de préférences va être créé avec les valeurs par défaut.
->Impossible d'importer les préférences
19:37:33.196 [ResipApp] ERROR  - Resip.GraphicApp: Erreur fatale, impossible de manipuler les préférences 
->Panic: Can't create a default preferences file, stop

**Comment by JSLair** [comment]
Ce comportement n'est en effet pas normal...
Est-ce que Resip a bien les droits d'écriture sur l'arborescence /home/pascal/.Resip/ ?
Pouvez-vous refaire le test avec la toute dernière version (j'ai amélioré le rapport d'erreur)?

En possible contournement voici le fichier a renommer "ResipPreferences.properties" et à mettre dans votre cas à cet endroit: /home/pascal/.Resip/ResipPreferences.properties.

[ResipPreferences.txt](https://github.com/ProgrammeVitam/sedatools/files/3643574/ResipPreferences.txt)

**Comment by akakeronos** [comment]
> Ce comportement n'est en effet pas normal...
> Est-ce que Resip a bien les droits d'écriture sur l'arborescence /home/pascal/.Resip/ ?
A priori oui c'est le répertoire home du user qui lance resip
> Pouvez-vous refaire le test avec la toute dernière version (j'ai amélioré le rapport d'erreur)?
Je dois télécharger les modifs du dépôt sedatools et refaire la séquence de build ? 
> En possible contournement voici le fichier a renommer "ResipPreferences.properties" et à mettre dans votre cas à cet endroit: /home/pascal/.Resip/ResipPreferences.properties.
> 
cela a fonctionné merci !!

java -jar target/resip-2.0.0-SNAPSHOT-shaded.jar -d /home/pascal/Nextcloud/01-docs-admin/  -w tmp
22:11:53.573 [ResipApp] INFO  GLOBAL - Début du journal au niveau=GLOBAL
22:11:53.581 [ResipApp] INFO  GLOBAL - Resip.GraphicApp: Le fichier de préférences global "ResipPreferences.properties" n'a pas été trouvé. Recherche de la version personnelle.
->Impossible d'importer les préférences
22:11:55.491 [ResipApp] INFO  GLOBAL - sedalib: début de l'import d'un ArchiveTransfer depuis une hiérarchie sur disque avec les racines en [/home/pascal/Nextcloud/01-docs-admin/03-serveur,

**Comment by JSLair** [comment]
Oui si vous pouviez télécharger les modifs du dépôt sedatools et refaire la séquence de build, avant de relancer sans le fichier de préférences cela me donnerais une indication du problème à la base...

PS: êtes-vous le Pascal Romain que j'avais croisé au CG33?

**Comment by akakeronos** [comment]
> Oui si vous pouviez télécharger les modifs du dépôt sedatools et refaire la séquence de build, avant de relancer sans le fichier de préférences cela me donnerais une indication du problème à la base...

ok

> PS: êtes-vous le Pascal Romain que j'avais croisé au CG33?

Oui :) Je suis maintenant consultant au sein de la société de conseil Rhizome-data

**Comment by akakeronos** [comment]
Non effectivement cela ne fonctionne pas encore correctement car une seule ligne (56) du fichier csv est traitée

sedalib: début de l'import du fichier csv de métadonnées
en [/home/pascal/Resip/dossierTravailCeline-RESIP_1569306470214.csv]
date=24 sept. 2019 16:20:17
sedalib: archiveUnit [55] n'a pas de parent, elle est mise en racine
sedalib: import du fichier csv de métadonnées terminé
[dossierTravailCeline-RESIP_1569306470214.txt](https://github.com/ProgrammeVitam/sedatools/files/3647689/dossierTravailCeline-RESIP_1569306470214.txt)
