### ISSUE TITLE
Balises non conformes au SEDA

### ISSUE THREAD

**Issue by aurelienlarne** [ProgrammeVitam/sedatools#17]
Bonjour,
Je vous fait part du problème rencontré suivant :

Les balises « Description Level », « EndDate » et « StartDate » des pièces jointes extraites d’éléments d’agenda, qui sont renseignées automatiquement par l’outil,ne sont pas conformes au SEDA et doivent être reprises manuellement. 

En vous remerciant pour votre retour,

**Comment by JSLair** [comment]
Ce problème est a priori corrigé depuis le 23/09/2019. Utilisez au moins la version 2.2.0-SNAPSHOT

JS Lair
