### ISSUE TITLE
import csv de métadonnées depuis Archifiltre

### ISSUE THREAD

**Issue by akakeronos** [ProgrammeVitam/sedatools#2]
Lorsque l'on génère un export csv de métadonnées depuis Resip on a une colonne Path qui indique le chemin des fichiers relativement au dossier analysé
Lorsque l'in génère un export RESIP depuis Archifiltre on a une colonne File qui indique le chemin des fichiers relativement au dossier analysé
Si on essaye de modifier manuellement l'export d'archifiltre pour renommer la colonne de File vers Path et que l'on utilise la fonction importer un csv de métadonnées dans Resip on a une erreur 

resip: erreur durant l'import, les données n'ont pas été modifiées
-> Le header [Path|Content.DescriptionLevel|Content.Title] est mal formatté. Il doit contenir au début soit une colonne File, soit deux colonnes File et ParentFile, soit trois colonnes ID, File et ParentFile ou ID, File et ParentID.

Cela signifie au passage que Resip ne peut pas importer de fichier csv de métadonnées à partir de fichiers générés dans Resip via la fonction export csv de métadonnées :)

Le résultat est que le fichier généré par Archifiltre est mal interprété par Resip et l'ensemble des lignes du tableau csv est considéré comme un archiveUnit au lieu de la distinction attendue entre archiveUnit et DataObject

Quel serait la structure du fichier csv de métadonnées pour permettre un import des métadonnées saisies dans Archifiltre ? De plus ne faudrait-il pas que cet export indique les chemins absolus des fichiers et sous-dossiers plutôt qu'un chemin relatif au dossier analysé ?

**Comment by JSLair** [comment]
Pour ce qui est du bon format de fichier CSV il y a deux exemples dans les jeux de test (oui je sais un peu de ménage serait utile...) dans
https://github.com/ProgrammeVitam/sedatools/tree/master/sedalib/src/test/resources/PacketSamples
les fichiers MetadataTestOK1col.csv et MetadataTestOK3col.csv

Pour ce qui est des chemins il a été fait le choix de les mettre en relatif par rapport au répertoire du fichier CSV de métadonnées pour que l'ensemble puisse être déplacé en restant cohérent.

Enfin la différence Path/File a été faite à dessein pour éviter de confondre les deux. Par ailleurs il faudrait que je replonge dans le code, mais il y a des choix de simplification qui ont du être fait dans l'export (dont l'objectif est un usage humain) qui ne garantissent donc pas une parfaite cohérence en cas d'import circulaire comme tu l'évoques.

**Comment by akakeronos** [comment]
Merci pour ces ressources et infos. Si on répartissait les fonctionnalités de manière claire on pourrait renforcer la partie exploration et "reclassement" d'arborescence dans Archifitre et génération du SIP dans Resip ? A voir sur la partie vocabulaires et règles de gestion s'il est nécessaire/pertinent de la maintenir dans les 2 outils

**Comment by JSLair** [comment]
A voir avec l'équipe d'Archifiltre dans une séance de conception...
