### ISSUE TITLE
Documentation pour le build incomplète

### ISSUE THREAD

**Issue by sviscapi** [ProgrammeVitam/sedatools#22]
Bonjour,

Est-ce que vous pourriez s'il vous plaît ajouter un petit peu de documentation concernant la procédure de build des sedatools ?

> Build
Avec un JDK 1.8, git, maven et gpg installés, la séquence de build est la suivante:

La partie sur GPG est notamment incomplète (à mon avis):

- gpg doit être installé, mais une paire de clé doit aussi être générée:

```
gpg --gen-key
```
Pour pouvoir décrypter la clé privée, la commande "mvn" à passer devient donc:

```
mvn clean install -Dgpg.passphrase=thephrase
```
Sans ces deux étapes le build échoue faute de pouvoir trouver une clé GPG ou de pouvoir la décrypter.

Merci, Samuel du CINES

P.S: et toujours bon courage pour le confinement :)

**Comment by JSLair** [comment]
Bonjour,

Solution plus simple à ce stade enlever dans javalibpst le processus de signature qui n'apporte vraiment rien...

Fait dans le commit https://github.com/ProgrammeVitam/java-libpst-origin/commit/00ee96fa11a2e56117844764808a73f45e16b1c0

La doc de build revue aussi pour enlever la dépendance gpg.

Merci

**Comment by sviscapi** [comment]
Bonsoir et merci,

Samuel
